name = "lotserver-license-generator"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Configure environment
[vars]
# Add any environment variables here

# Define routes or add custom domains
# routes = []
# custom_domain = "license.example.com"

# Customize worker configuration
[build]
command = ""

[triggers]
crons = []